src/src/Entity/BlogPost.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogPostRepository")
 */
class BlogPost
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $summary;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\Column(type="datetime")
     */
    private $creation_date;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $creator_id;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_visible;

    /**
     * @ORM\Column(type="boolean")
     */
    private $logged_users_only;

    /**
     * @ORM\Column(type="boolean")
     */
    private $allow_comment;

    /**
     * @ORM\Column(type="boolean")
     */
    private $allow_comment_anonymous;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comments", mappedBy="post")
     */
    private $comments;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreationDate(): ?\DateTimeInterface
    {
        return $this->creation_date;
    }

    public function setCreationDate(\DateTimeInterface $creation_date): self
    {
        $this->creation_date = $creation_date;

        return $this;
    }

    public function getCreatorId(): ?int
    {
        return $this->creator_id;
    }

    public function setCreatorId(?int $creator_id): self
    {
        $this->creator_id = $creator_id;

        return $this;
    }

    public function getIsVisible(): ?bool
    {
        return $this->is_visible;
    }

    public function setIsVisible(bool $is_visible): self
    {
        $this->is_visible = $is_visible;

        return $this;
    }

    public function getLoggedUsersOnly(): ?int
    {
        return $this->logged_users_only;
    }

    public function setLoggedUsersOnly(int $logged_users_only): self
    {
        $this->logged_users_only = $logged_users_only;

        return $this;
    }

    public function getAllowComment(): ?int
    {
        return $this->allow_comment;
    }

    public function setAllowComment(int $allow_comment): self
    {
        $this->allow_comment = $allow_comment;

        return $this;
    }

    public function getAllowCommentAnonymous(): ?int
    {
        return $this->allow_comment_anonymous;
    }

    public function setAllowCommentAnonymous(int $allow_comment_anonymous): self
    {
        $this->allow_comment_anonymous = $allow_comment_anonymous;

        return $this;
    }

    /**
     * @return Collection|Comments[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comments $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comments $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }
}

src/src/Controller/EtiController.php
<?php

namespace App\Controller;

use App\Entity\BlogPost;
use App\Entity\Comments;
use App\Entity\User;
use App\Form\AddCommentType;
use App\Form\AddPostType;
use App\Form\EditPostType;
use App\Repository\BlogPostRepository;
use App\Repository\CommentsRepository;
use Exception;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Contracts\Translation\TranslatorInterface;
use Symfony\Component\HttpFoundation\Session\SessionInterface;


/**
 * Class EtiController
 */
class EtiController extends AbstractController
{
    /**
     * @Route("/", name="homepage")
     * @return Response
     */
    public function blogHomepage()
    {
        return $this->render('eti/blog/homepage.html.twig');
    }

    /**
     * @Route("/first/page", name="first_page")
     * @param TranslatorInterface $translator
     * @return Response
     * @throws Exception
     */
    public function randomNumber(TranslatorInterface $translator)
    {
        $number = random_int(0, 100);

        return $this->render('eti/blog/first_page.html.twig', [
            'number' => $number,
            'translated_php' => $translator->trans('Translated string'),
            'translated_php_pl' => $translator->trans('Translated string', [], 'messages', 'pl_PL')
        ]);
    }


    /**
     * @Route("posts/list", name="post_listing")
     *
     * @return Response
     * @throws Exception
     */
    public function listBlogPosts()
    {
        $repository = $this->getDoctrine()->getRepository(BlogPost::class);
        $articles = $repository->findBy([
            'is_visible'=>'1'
        ]);

        return $this->render('eti/blog/posts.html.twig', [
            'articles' => $articles
        ]);
    }


    /**
     * @Route("posts/view/{id}", name="post_details", requirements={"id":"\d+"})
     * @param $id
     * @param Request $request
     * @param User $user
     * @param BlogPost $post
     * @param CommentsRepository $commentsRepository
     * @return Response
     */
    public function postDetails($id, Request $request, User $user, BlogPost $post, CommentsRepository $commentsRepository)
    {
        $article = $this->getDoctrine()->getRepository(BlogPost::class)->find($id);

        if(!$article)
        {
            throw $this->createNotFoundException('No article found for id'.$id);
        }

        $newComment = new Comments();
        $comments = $commentsRepository->findBy(['post' => $post]);
        $form = $this->createForm(AddCommentType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $content = $form->getData()->getContent();

            if ($this->getUser() == true)
            {
                $userName = $this->getUser()->getUsername();


            }
            else {
                $userName = null;
                $idUser = null;
            }


            $newComment->setUsername($userName);
            $newComment->setContent($content);
            $newComment->setCreationDate(new \DateTime());
            $newComment->setUser($user);
            $newComment->setPost($post);


            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($newComment);
            $entityManager->flush();




            $this->addFlash('notice','Your comment has been added!');

        }



        return $this->render('eti/blog/post_view.html.twig', [
            'articles' => $article,
            'form' => $form->createView(),
            'comments' => $comments

        ]);
    }

    /**
    * @Route("secret/area", name="secret_area")
     */

    public function secretArea()
    {
        $post = $this->getDoctrine()->getRepository(BlogPost::class)->findBy([
            'logged_users_only' => '1'
        ]);

        return $this->render('eti/blog/secret_area.html.twig', [
          'posts' => $post
        ]);
    }

    /**
     * @Route("posts/add", name="add_post")
     * @param Request $request
     * @return Response
     */

    public function addPost(Request $request)
    {
        $post = new BlogPost();
        $id = $this->getUser()->getId();

        $form = $this->createForm(AddPostType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $title = $form->getData()->getTitle();
            $summary = $form->getData()->getSummary();
            $content = $form->getData()->getContent();
            $isVisible = $form->getData()->getIsVisible();
            $forLogged = $form->getData()->getLoggedUsersOnly();
            $allowComment = $form->getData()->getAllowComment();
            $allowCommentAnonymous= $form->getData()->getAllowCommentAnonymous();

            $post->setTitle($title);
            $post->setSummary($summary);
            $post->setContent($content);
            $post->setCreationDate(new \DateTime());
            $post->setCreatorId($id);
            $post->setIsVisible($isVisible);
            $post->setLoggedUsersOnly($forLogged);
            $post->setAllowComment($allowComment);
            $post->setAllowCommentAnonymous($allowCommentAnonymous);

            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($post);
            $entityManager->flush();

            $this->addFlash('notice','Your post was added!');
        }

        return $this->render('eti/blog/add_post.html.twig', [
           'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("posts/edit/{id}", name="edit_post")
     * @param BlogPost $blogPost
     * @param Request $request
     * @return Response
     */


    public function editPost(BlogPost $blogPost, Request $request, $id)
    {
        $user_id = $this->getUser()->getId();
        $creator_id = $blogPost->getCreatorId();

        if ($user_id != $creator_id)
        {
            $this->render('errors/401.html.twig');
        }



        $entityManager = $this->getDoctrine()->getManager();
        $postManager = $entityManager->getRepository(BlogPost::class)->find($id);

        $form = $this->createForm(EditPostType::class, $postManager);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid())
        {
            $title = $form->getData()->getTitle();
            $summary = $form->getData()->getSummary();
            $content = $form->getData()->getContent();
            $isVisible = $form->getData()->getIsVisible();


            $postManager->setTitle($title);
            $postManager->setSummary($summary);
            $postManager->setContent($content);
            $postManager->setIsVisible($isVisible);


            $entityManager->persist($postManager);
            $entityManager->flush();

            $this->addFlash('notice','Your changes were saved!');
        }

        return $this->render('eti/blog/edit_post.html.twig',[
           'form' => $form->createView(),
        ]);

    }
}

src/templates/eti/blog/add_post.html.twig
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / Add your article{% endblock %}

{% block content %}
    {% for message in app.flashes('notice') %}
    <div class="flash-notice">
        {{ message }}
    </div>
    {% endfor %}
    <h1> Add article: </h1>

    <p>{{ form(form) }}</p>


{% endblock %}

src/templates/eti/blog/edit_post.html.twig
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / Add your article{% endblock %}

{% block content %}
    {% for message in app.flashes('notice') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}
    <h1> Edit article: </h1>

    <p>{{ form(form) }}</p>


{% endblock %}

src/templates/eti/blog/first_page.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / FirstPage{% endblock %}

{% block content %}
    <p> Lucky number: {{ number }} </p>
    <div>
        <p>Default PHP translation: {{ translated_php }} <br />
        Template translation: {% trans %}Translated string{% endtrans %}</p>
    </div>
    <div>
        <p>Forced PL translation: {{ translated_php_pl }}<br />
        PL Forced Template translation: {{ 'Translated string'|trans({}, 'messages', 'pl_PL') }}</p>
    </div>
{% endblock %}

src/templates/eti/blog/homepage.html.twig
{# templates/eti/blog/homepage.html.twig #}

{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Homepage{% endblock %}

{% block content %}
    <p> Hello, this is ETI's homepage! </p>
{% endblock %}

src/templates/eti/blog/layout.html.twig
{# templates/blog/layout.html.twig #}
{% extends 'base.html.twig' %}

{% block body %}
    <h1>ETI Blog</h1>

    {% block content %}{% endblock %}
{% endblock %}

src/templates/eti/blog/post_view.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / Articles to read{% endblock %}

{% block content %}
    <p> Posts: </p>

    <ul>
        <h1>Content:</h1>
        <p>{{ articles.content }}</p>
    </ul>
    <h2>Comments:</h2>
    {% for message in app.flashes('notice') %}
        <div class="flash-notice">
            {{ message }}
        </div>
    {% endfor %}
    {% if articles.allowCommentAnonymous == true or articles.allowComment == true and app.user != null %}
        {{ form(form) }}
    {% elseif articles.allowCommentAnonymous == false and articles.allowComment == true %}
        You must log on to comment on this post
    {% elseif articles.allowCommentAnonymous == false and articles.allowComment == false %}
        Comments off
    {% endif %}
    <p> Comments: </p>
    {% for comment in comments %}
        <ul>
            <li>{{ comment.username }}</li>
            <li>{{ comment.creationDate|date("m/d/Y H:m:i", false) }}</li>
            <li>{{ comment.content }}</li>
            <br><br>
        </ul>
    {% endfor %}


{% endblock %}

src/templates/eti/blog/posts.html.twig
{# templates/blog/first_page.html.twig #}
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Blog Index / Articles to read{% endblock %}

{% block content %}
    {% if app.user %}
    <h1><a href="{{ path('add_post')}}">Add your Post!</a></h1>>
    {% endif %}
    <p> Posts: </p>
    <ul>
    {% for article in articles %}
        <li>
            <a href="{{ path('post_details', {'id': article.id }) }}">
                {{ article.title }} - {{ article.summary }}
            </a> --->
            {% if app.user and article.creatorId == app.user.id %}
                <a href="{{ path ('edit_post', {'id': article.id}) }}">
                    Edit
                </a>
            {% endif %}
        </li>
    {% endfor %}
    </ul>
{% endblock %}

src/templates/eti/blog/secret_area.html.twig
{% extends 'eti/blog/layout.html.twig' %}

{% block title %}Caution! This is Secret Area!!!{% endblock %}

{% block content %}

    Posts in secret area:
{% for post in posts %}
    <li>
        <a href="{{ path('post_details', {'id': post.id }) }}">
            {{ post.title }} - {{ post.summary }}
        </a>
    </li>
    {% endfor %}
{% endblock %}